In [1]:
import numpy as np

import scipy
from statsmodels.stats.weightstats import *
from statsmodels.stats.proportion import proportion_confint

In [199]:
Test = [1] * 10 + [0] * 24

In [200]:
Control = [1] * 4 + [0] * 12

In [201]:
def proportions_diff_z_stat_ind(sample1, sample2):
    n1 = len(sample1)
    n2 = len(sample2)
    
    p1 = float(sum(sample1)) / n1
    p2 = float(sum(sample2)) / n2 
    P = float(p1*n1 + p2*n2) / (n1 + n2)
    
    return (p1 - p2) / np.sqrt(P * (1 - P) * (1. / n1 + 1. / n2))

In [202]:
def proportions_diff_z_test(z_stat, alternative = 'two-sided'):
    if alternative not in ('two-sided', 'less', 'greater'):
        raise ValueError("alternative not recognized\n"
                         "should be 'two-sided', 'less' or 'greater'")
    
    if alternative == 'two-sided':
        return 2 * (1 - scipy.stats.norm.cdf(np.abs(z_stat)))
    
    if alternative == 'less':
        return scipy.stats.norm.cdf(z_stat)

    if alternative == 'greater':
        return 1 - scipy.stats.norm.cdf(z_stat)

In [203]:
Q = round(proportions_diff_z_test(proportions_diff_z_stat_ind(Test, Control)), 4)
Q

0.7459

In [69]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split

In [64]:
data = pd.read_csv('banknotes.txt', header = 0, sep = '\t')

In [65]:
data.head()

X1     X2     X3    X4    X5     X6  real
0  214.8  131.0  131.1   9.0   9.7  141.0     1
1  214.6  129.7  129.7   8.1   9.5  141.7     1
2  214.8  129.7  129.7   8.7   9.6  142.2     1
3  214.8  129.7  129.6   7.5  10.4  142.0     1
4  215.0  129.6  129.7  10.4   7.7  141.8     1

In [85]:
df = data.iloc[:, :-1]
y = data[['real']]

In [87]:
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.25, random_state=1)

In [91]:
X_train1 = X_train[['X1', 'X2', 'X3']]
X_test1 = X_test[['X1', 'X2', 'X3']]

X_train2 = X_train[['X4', 'X5', 'X6']]
X_test2 = X_test[['X4', 'X5', 'X6']]

In [95]:
regr1 = LogisticRegression()
regr1.fit(X_train1, y_train)

C:\Anaconda2\lib\site-packages\sklearn\utils\validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [101]:
regrPredict1 = regr1.predict(X_test1)

In [102]:
regrPredict1

array([1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0], dtype=int64)

In [103]:
regr2 = LogisticRegression()
regr2.fit(X_train2, y_train)

C:\Anaconda2\lib\site-packages\sklearn\utils\validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [104]:
regrPredict2 = regr2.predict(X_test2)

In [105]:
regrPredict2

array([1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0], dtype=int64)

In [136]:
Ytest = y_test.iloc

In [172]:
Z1 = np.random.randint(low = 1, high = 2, size=50)
Z2 = np.random.randint(low = 1, high = 2, size=50)

In [174]:
for i in range(len(y_test)):
    if regrPredict1[i] == int(Ytest[i]):
        Z1[i] = 0

In [175]:
Z1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0])

In [176]:
for i in range(len(y_test)):
    if regrPredict2[i] == int(Ytest[i]):
        Z2[i] = 0

In [177]:
Z2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0])

In [178]:
def proportions_diff_confint_rel(sample1, sample2, alpha = 0.05):
    z = scipy.stats.norm.ppf(1 - alpha / 2.)
    sample = zip(sample1, sample2)
    n = len(sample)
        
    f = sum([1 if (x[0] == 1 and x[1] == 0) else 0 for x in sample])
    g = sum([1 if (x[0] == 0 and x[1] == 1) else 0 for x in sample])
    
    left_boundary = float(f - g) / n  - z * np.sqrt(float((f + g)) / n**2 - float((f - g)**2) / n**3)
    right_boundary = float(f - g) / n  + z * np.sqrt(float((f + g)) / n**2 - float((f - g)**2) / n**3)
    return (left_boundary, right_boundary)

In [179]:
def proportions_diff_z_stat_rel(sample1, sample2):
    sample = zip(sample1, sample2)
    n = len(sample)
    
    f = sum([1 if (x[0] == 1 and x[1] == 0) else 0 for x in sample])
    g = sum([1 if (x[0] == 0 and x[1] == 1) else 0 for x in sample])
    
    return float(f - g) / np.sqrt(f + g - float((f - g)**2) / n )

In [182]:
print "95%% confidence interval for a difference between proportions: [%f, %f]" \
      % proportions_diff_confint_rel(Z1, Z2)

95% confidence interval for a difference between proportions: [0.059945, 0.300055]


In [183]:
confInt = proportions_diff_confint_rel(Z1, Z2)
confInt

(0.059945206279614305, 0.30005479372038568)

In [184]:
round(confInt[0], 4)

0.0599

In [185]:
print "p-value: %f" % proportions_diff_z_test(proportions_diff_z_stat_rel(Z1, Z2))

p-value: 0.003297


In [186]:
pValue = proportions_diff_z_test(proportions_diff_z_stat_rel(Z1, Z2))
pValue

0.0032969384555543435

In [190]:
import math

In [193]:
z = (541.4 - 525) / (100 / math.sqrt(100))
print z

1.64


In [194]:
pValue = 1 - scipy.stats.norm.cdf(z)
round(pValue, 4)

0.0505

In [196]:
z = (541.5 - 525) / (100 / math.sqrt(100))
print z

1.65


In [197]:
pValue = 1 - scipy.stats.norm.cdf(z)
round(pValue, 4)

0.0495